apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "anton.fullname" . }}-orchestrator
  namespace: {{ include "anton.runnerNamespace" . }}
  labels:
    {{- include "anton.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
