apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anton.fullname" . }}-orchestrator
  namespace: {{ include "anton.namespace" . }}
  labels:
    {{- include "anton.labels" . | nindent 4 }}
    {{- include "anton.selectorLabels" (dict "context" . "component" "orchestrator") | nindent 4 }}
