apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "anton.fullname" . }}-orchestrator
  namespace: {{ include "anton.runnerNamespace" . }}
  labels:
    {{- include "anton.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "anton.fullname" . }}-orchestrator
subjects:
  - kind: ServiceAccount
    name: {{ include "anton.fullname" . }}-orchestrator
    namespace: {{ include "anton.namespace" . }}
